[2024-10-08T21:02:52.265+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-08T21:02:52.283+0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lr_train.get_data manual__2024-10-08T16:02:47.532334+00:00 [queued]>
[2024-10-08T21:02:52.289+0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lr_train.get_data manual__2024-10-08T16:02:47.532334+00:00 [queued]>
[2024-10-08T21:02:52.290+0500] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-10-08T21:02:52.301+0500] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): get_data> on 2024-10-08 16:02:47.532334+00:00
[2024-10-08T21:02:52.313+0500] {logging_mixin.py:190} WARNING - /home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=20557) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-08T21:02:52.314+0500] {standard_task_runner.py:72} INFO - Started process 20642 to run task
[2024-10-08T21:02:52.314+0500] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'lr_train', 'get_data', 'manual__2024-10-08T16:02:47.532334+00:00', '--job-id', '823', '--raw', '--subdir', 'DAGS_FOLDER/train_models.py', '--cfg-path', '/tmp/tmpxmew7kjk']
[2024-10-08T21:02:52.315+0500] {standard_task_runner.py:105} INFO - Job 823: Subtask get_data
[2024-10-08T21:02:52.367+0500] {task_command.py:467} INFO - Running <TaskInstance: lr_train.get_data manual__2024-10-08T16:02:47.532334+00:00 [running]> on host nicolaspc-HP-Pavilion-Laptop-15-eh1xxx
[2024-10-08T21:02:52.450+0500] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nicolas Pal' AIRFLOW_CTX_DAG_ID='lr_train' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T16:02:47.532334+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-08T16:02:47.532334+00:00'
[2024-10-08T21:02:52.451+0500] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-08T21:02:52.640+0500] {base.py:84} INFO - Retrieving connection 'pg_connection'
[2024-10-08T21:02:52.666+0500] {base.py:84} INFO - Retrieving connection 's3_connection'
[2024-10-08T21:02:52.666+0500] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-10-08T21:02:59.794+0500] {train_models.py:108} INFO - Данные загружены из б/д и сохранены на S3
[2024-10-08T21:02:59.796+0500] {python.py:240} INFO - Done. Returned value was: {'model': 'lr', 'start_timestamp': '20241008 21:02', 'experiment_id': '141', 'get_data_start': '20241008 21:02', 'get_data_end': '20241008 21:02', 'data_shape': (20640, 9)}
[2024-10-08T21:02:59.831+0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-08T21:02:59.831+0500] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=lr_train, task_id=get_data, run_id=manual__2024-10-08T16:02:47.532334+00:00, execution_date=20241008T160247, start_date=20241008T160252, end_date=20241008T160259
[2024-10-08T21:02:59.866+0500] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-10-08T21:02:59.901+0500] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-08T21:02:59.904+0500] {local_task_job_runner.py:240} INFO - ::endgroup::
