[2024-08-21T12:08:04.719+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-21T12:08:04.743+0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 3_models_dag.prepare_data scheduled__2024-08-20T01:00:00+00:00 [queued]>
[2024-08-21T12:08:04.753+0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 3_models_dag.prepare_data scheduled__2024-08-20T01:00:00+00:00 [queued]>
[2024-08-21T12:08:04.753+0500] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-08-21T12:08:04.766+0500] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): prepare_data> on 2024-08-20 01:00:00+00:00
[2024-08-21T12:08:04.780+0500] {logging_mixin.py:190} WARNING - /home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=18847) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-21T12:08:04.781+0500] {standard_task_runner.py:72} INFO - Started process 18965 to run task
[2024-08-21T12:08:04.781+0500] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '3_models_dag', 'prepare_data', 'scheduled__2024-08-20T01:00:00+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/train_models-2-checkpoint.py', '--cfg-path', '/tmp/tmp8_gm6krd']
[2024-08-21T12:08:04.783+0500] {standard_task_runner.py:105} INFO - Job 67: Subtask prepare_data
[2024-08-21T12:08:04.851+0500] {task_command.py:467} INFO - Running <TaskInstance: 3_models_dag.prepare_data scheduled__2024-08-20T01:00:00+00:00 [running]> on host nicolaspc-HP-Pavilion-Laptop-15-eh1xxx
[2024-08-21T12:08:04.959+0500] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nicolas Pal' AIRFLOW_CTX_DAG_ID='3_models_dag' AIRFLOW_CTX_TASK_ID='prepare_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-20T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-20T01:00:00+00:00'
[2024-08-21T12:08:04.960+0500] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-21T12:08:04.990+0500] {python.py:240} INFO - Done. Returned value was: {'start_tiemstamp': '20240821 12:07', 'data_download_start': '20240821 12:08', 'data_download_end': '20240821 12:08'}
[2024-08-21T12:08:05.022+0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-21T12:08:05.023+0500] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=3_models_dag, task_id=prepare_data, run_id=scheduled__2024-08-20T01:00:00+00:00, execution_date=20240820T010000, start_date=20240821T070804, end_date=20240821T070805
[2024-08-21T12:08:05.081+0500] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-21T12:08:05.108+0500] {taskinstance.py:3891} INFO - 3 downstream tasks scheduled from follow-on schedule check
[2024-08-21T12:08:05.111+0500] {local_task_job_runner.py:240} INFO - ::endgroup::
