[2024-10-08T21:12:44.337+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-08T21:12:44.355+0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rf_train.get_data manual__2024-10-08T16:12:39.095636+00:00 [queued]>
[2024-10-08T21:12:44.361+0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rf_train.get_data manual__2024-10-08T16:12:39.095636+00:00 [queued]>
[2024-10-08T21:12:44.362+0500] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-10-08T21:12:44.374+0500] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): get_data> on 2024-10-08 16:12:39.095636+00:00
[2024-10-08T21:12:44.386+0500] {logging_mixin.py:190} WARNING - /home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=29135) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-08T21:12:44.387+0500] {standard_task_runner.py:72} INFO - Started process 29186 to run task
[2024-10-08T21:12:44.387+0500] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'rf_train', 'get_data', 'manual__2024-10-08T16:12:39.095636+00:00', '--job-id', '839', '--raw', '--subdir', 'DAGS_FOLDER/train_models.py', '--cfg-path', '/tmp/tmprrrw4jnl']
[2024-10-08T21:12:44.390+0500] {standard_task_runner.py:105} INFO - Job 839: Subtask get_data
[2024-10-08T21:12:44.442+0500] {task_command.py:467} INFO - Running <TaskInstance: rf_train.get_data manual__2024-10-08T16:12:39.095636+00:00 [running]> on host nicolaspc-HP-Pavilion-Laptop-15-eh1xxx
[2024-10-08T21:12:44.532+0500] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nicolas Pal' AIRFLOW_CTX_DAG_ID='rf_train' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T16:12:39.095636+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-08T16:12:39.095636+00:00'
[2024-10-08T21:12:44.533+0500] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-08T21:12:44.708+0500] {base.py:84} INFO - Retrieving connection 'pg_connection'
[2024-10-08T21:12:44.740+0500] {base.py:84} INFO - Retrieving connection 's3_connection'
[2024-10-08T21:12:44.740+0500] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-10-08T21:12:51.498+0500] {train_models.py:108} INFO - Данные загружены из б/д и сохранены на S3
[2024-10-08T21:12:51.500+0500] {python.py:240} INFO - Done. Returned value was: {'model': 'rf', 'start_timestamp': '20241008 21:12', 'experiment_id': '142', 'get_data_start': '20241008 21:12', 'get_data_end': '20241008 21:12', 'data_shape': (20640, 9)}
[2024-10-08T21:12:51.539+0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-08T21:12:51.539+0500] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=rf_train, task_id=get_data, run_id=manual__2024-10-08T16:12:39.095636+00:00, execution_date=20241008T161239, start_date=20241008T161244, end_date=20241008T161251
[2024-10-08T21:12:51.578+0500] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-10-08T21:12:51.603+0500] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-08T21:12:51.606+0500] {local_task_job_runner.py:240} INFO - ::endgroup::
