[2024-09-19T08:12:49.689+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-19T08:12:49.709+0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 3_models_dag.prepare_data scheduled__2024-09-18T01:00:00+00:00 [queued]>
[2024-09-19T08:12:49.717+0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 3_models_dag.prepare_data scheduled__2024-09-18T01:00:00+00:00 [queued]>
[2024-09-19T08:12:49.717+0500] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-09-19T08:12:49.730+0500] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): prepare_data> on 2024-09-18 01:00:00+00:00
[2024-09-19T08:12:49.744+0500] {logging_mixin.py:190} WARNING - /home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=10010) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-19T08:12:49.745+0500] {standard_task_runner.py:72} INFO - Started process 10053 to run task
[2024-09-19T08:12:49.744+0500] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '3_models_dag', 'prepare_data', 'scheduled__2024-09-18T01:00:00+00:00', '--job-id', '274', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/train_models-2-checkpoint.py', '--cfg-path', '/tmp/tmpxgsnt2n2']
[2024-09-19T08:12:49.746+0500] {standard_task_runner.py:105} INFO - Job 274: Subtask prepare_data
[2024-09-19T08:12:49.798+0500] {task_command.py:467} INFO - Running <TaskInstance: 3_models_dag.prepare_data scheduled__2024-09-18T01:00:00+00:00 [running]> on host nicolaspc-HP-Pavilion-Laptop-15-eh1xxx
[2024-09-19T08:12:49.887+0500] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nicolas Pal' AIRFLOW_CTX_DAG_ID='3_models_dag' AIRFLOW_CTX_TASK_ID='prepare_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-18T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-18T01:00:00+00:00'
[2024-09-19T08:12:49.888+0500] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-19T08:12:49.913+0500] {s3.py:1387} INFO - Downloading source S3 file from Bucket test-bucket-nicolas-1 with path datasets/california_housing.pkl
[2024-09-19T08:12:49.927+0500] {base.py:84} INFO - Retrieving connection 'aws_default'
[2024-09-19T08:12:49.927+0500] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2024-09-19T08:12:53.935+0500] {train_models-2-checkpoint.py:120} INFO - Data preparation finished.
[2024-09-19T08:12:53.937+0500] {python.py:240} INFO - Done. Returned value was: {'start_tiemstamp': '20240919 08:12', 'data_download_start': '20240919 08:12', 'data_download_end': '20240919 08:12', 'data_preparation_end': '20240919 08:12'}
[2024-09-19T08:12:53.966+0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-19T08:12:53.966+0500] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=3_models_dag, task_id=prepare_data, run_id=scheduled__2024-09-18T01:00:00+00:00, execution_date=20240918T010000, start_date=20240919T031249, end_date=20240919T031253
[2024-09-19T08:12:54.011+0500] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-19T08:12:54.038+0500] {taskinstance.py:3891} INFO - 3 downstream tasks scheduled from follow-on schedule check
[2024-09-19T08:12:54.041+0500] {local_task_job_runner.py:240} INFO - ::endgroup::
