[2024-08-21T12:07:57.825+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-21T12:07:57.844+0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train.init scheduled__2024-08-19T01:00:00+00:00 [queued]>
[2024-08-21T12:07:57.853+0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train.init scheduled__2024-08-19T01:00:00+00:00 [queued]>
[2024-08-21T12:07:57.854+0500] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-08-21T12:07:57.870+0500] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): init> on 2024-08-19 01:00:00+00:00
[2024-08-21T12:07:57.899+0500] {logging_mixin.py:190} WARNING - /home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=18386) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-21T12:07:57.901+0500] {standard_task_runner.py:72} INFO - Started process 18557 to run task
[2024-08-21T12:07:57.911+0500] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'train', 'init', 'scheduled__2024-08-19T01:00:00+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/train_dag-checkpoint.py', '--cfg-path', '/tmp/tmp_4skjfro']
[2024-08-21T12:07:57.917+0500] {standard_task_runner.py:105} INFO - Job 61: Subtask init
[2024-08-21T12:07:58.048+0500] {task_command.py:467} INFO - Running <TaskInstance: train.init scheduled__2024-08-19T01:00:00+00:00 [running]> on host nicolaspc-HP-Pavilion-Laptop-15-eh1xxx
[2024-08-21T12:07:58.158+0500] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nicolas Pal' AIRFLOW_CTX_DAG_ID='train' AIRFLOW_CTX_TASK_ID='init' AIRFLOW_CTX_EXECUTION_DATE='2024-08-19T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-19T01:00:00+00:00'
[2024-08-21T12:07:58.159+0500] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-21T12:07:58.198+0500] {base.py:84} INFO - Retrieving connection 'aws_default'
[2024-08-21T12:07:58.316+0500] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-08-21T12:08:01.835+0500] {train_dag-checkpoint.py:84} INFO - Data download finished.
[2024-08-21T12:08:01.838+0500] {python.py:240} INFO - Done. Returned value was: None
[2024-08-21T12:08:01.854+0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-21T12:08:01.854+0500] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=train, task_id=init, run_id=scheduled__2024-08-19T01:00:00+00:00, execution_date=20240819T010000, start_date=20240821T070757, end_date=20240821T070801
[2024-08-21T12:08:01.901+0500] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-21T12:08:01.930+0500] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-21T12:08:01.934+0500] {local_task_job_runner.py:240} INFO - ::endgroup::
