[2024-08-21T19:25:40.376+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-21T19:25:40.397+0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 3_models_dag_home.init manual__2024-08-21T14:25:38.859451+00:00 [queued]>
[2024-08-21T19:25:40.404+0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 3_models_dag_home.init manual__2024-08-21T14:25:38.859451+00:00 [queued]>
[2024-08-21T19:25:40.405+0500] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-08-21T19:25:40.415+0500] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): init> on 2024-08-21 14:25:38.859451+00:00
[2024-08-21T19:25:40.428+0500] {logging_mixin.py:190} WARNING - /home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=267813) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-21T19:25:40.429+0500] {standard_task_runner.py:72} INFO - Started process 267861 to run task
[2024-08-21T19:25:40.428+0500] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '3_models_dag_home', 'init', 'manual__2024-08-21T14:25:38.859451+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/homework_stepik-checkpoint.py', '--cfg-path', '/tmp/tmptdch76qa']
[2024-08-21T19:25:40.430+0500] {standard_task_runner.py:105} INFO - Job 121: Subtask init
[2024-08-21T19:25:40.487+0500] {task_command.py:467} INFO - Running <TaskInstance: 3_models_dag_home.init manual__2024-08-21T14:25:38.859451+00:00 [running]> on host nicolaspc-HP-Pavilion-Laptop-15-eh1xxx
[2024-08-21T19:25:40.566+0500] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nicolas Pal' AIRFLOW_CTX_DAG_ID='3_models_dag_home' AIRFLOW_CTX_TASK_ID='init' AIRFLOW_CTX_EXECUTION_DATE='2024-08-21T14:25:38.859451+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-21T14:25:38.859451+00:00'
[2024-08-21T19:25:40.568+0500] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-21T19:25:40.818+0500] {migration.py:216} INFO - Context impl PostgresqlImpl.
[2024-08-21T19:25:40.819+0500] {migration.py:219} INFO - Will assume transactional DDL.
[2024-08-21T19:25:40.863+0500] {python.py:240} INFO - Done. Returned value was: {'start_tiemstamp': '20240821 19:25'}
[2024-08-21T19:25:40.892+0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-21T19:25:40.893+0500] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=3_models_dag_home, task_id=init, run_id=manual__2024-08-21T14:25:38.859451+00:00, execution_date=20240821T142538, start_date=20240821T142540, end_date=20240821T142540
[2024-08-21T19:25:40.925+0500] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-21T19:25:40.957+0500] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-21T19:25:40.960+0500] {local_task_job_runner.py:240} INFO - ::endgroup::
