[2024-10-09T10:26:06.213+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-09T10:26:06.254+0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rf_train.get_data scheduled__2024-10-08T01:00:00+00:00 [queued]>
[2024-10-09T10:26:06.275+0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rf_train.get_data scheduled__2024-10-08T01:00:00+00:00 [queued]>
[2024-10-09T10:26:06.276+0500] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-10-09T10:26:06.297+0500] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): get_data> on 2024-10-08 01:00:00+00:00
[2024-10-09T10:26:06.318+0500] {logging_mixin.py:190} WARNING - /home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=8364) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-09T10:26:06.321+0500] {standard_task_runner.py:72} INFO - Started process 8492 to run task
[2024-10-09T10:26:06.326+0500] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'rf_train', 'get_data', 'scheduled__2024-10-08T01:00:00+00:00', '--job-id', '986', '--raw', '--subdir', 'DAGS_FOLDER/project_1.py', '--cfg-path', '/tmp/tmp4axc95vl']
[2024-10-09T10:26:06.343+0500] {standard_task_runner.py:105} INFO - Job 986: Subtask get_data
[2024-10-09T10:26:06.438+0500] {task_command.py:467} INFO - Running <TaskInstance: rf_train.get_data scheduled__2024-10-08T01:00:00+00:00 [running]> on host nicolaspc-HP-Pavilion-Laptop-15-eh1xxx
[2024-10-09T10:26:06.574+0500] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nicolas Pal' AIRFLOW_CTX_DAG_ID='rf_train' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-08T01:00:00+00:00'
[2024-10-09T10:26:06.575+0500] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-09T10:26:06.813+0500] {base.py:84} INFO - Retrieving connection 'pg_connection'
[2024-10-09T10:26:06.840+0500] {base.py:84} INFO - Retrieving connection 's3_connection'
[2024-10-09T10:26:06.841+0500] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-10-09T10:26:10.763+0500] {project_1.py:108} INFO - Данные загружены из б/д и сохранены на S3
[2024-10-09T10:26:10.766+0500] {python.py:240} INFO - Done. Returned value was: {'model': 'rf', 'start_timestamp': '20241009 10:26', 'experiment_id': '142', 'get_data_start': '20241009 10:26', 'get_data_end': '20241009 10:26', 'data_shape': (20640, 9)}
[2024-10-09T10:26:10.821+0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-09T10:26:10.821+0500] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=rf_train, task_id=get_data, run_id=scheduled__2024-10-08T01:00:00+00:00, execution_date=20241008T010000, start_date=20241009T052606, end_date=20241009T052610
[2024-10-09T10:26:10.863+0500] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-10-09T10:26:10.891+0500] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-09T10:26:10.894+0500] {local_task_job_runner.py:240} INFO - ::endgroup::
